version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: kanban_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban123
      POSTGRES_DB: kanban_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
